-- T9: Importação de 282 leads calçadistas Grande SP
-- Gerado em 01/04/2026 — NÃO executar sem revisar
-- Usar apenas leads sem email/whatsapp para campanha de telefone

BEGIN;

-- Criar origem 'prospecao_calcados_sp' se não existir
INSERT INTO origens_lead (nome, ativo)
SELECT 'Prospecção Calçados SP', true
WHERE NOT EXISTS (SELECT 1 FROM origens_lead WHERE nome = 'Prospecção Calçados SP');

-- Inserir leads (ignorar se empresa já existir com mesmo telefone)
INSERT INTO leads (empresa, contato_nome, telefone, contato_email, segmento, temperatura, origem_id, status, observacoes)
SELECT v.empresa, v.contato_nome, v.telefone, v.email, v.segmento, v.temperatura,
       (SELECT id FROM origens_lead WHERE nome = 'Prospecção Calçados SP' LIMIT 1),
       'novo', v.observacoes
FROM (VALUES
  ('Distribuidora Wilson - Atacadista de Calçados', 'Responsável Comercial', '+55 11 2322-3200', NULL, 'calcados_atacado', 'morno', 'Calçados SP | Atacadista | Brás, São Paulo | 4.5⭐'),
  ('Avacy Distribuidora', 'Responsável Comercial', '+55 11 5461-4932', NULL, 'calcados_varejo', 'morno', 'Calçados SP | Loja de calçado | Brás, São Paulo | 4.6⭐'),
  ('Vitória Distribuidora - Abelha Rainha', 'Responsável Comercial', '+55 11 4324-9170', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Serviço de distribuição | Vila Brasil, São Paulo | 4.3⭐'),
  ('Kseg Comercial Distribuidora de EPI em São Paulo', 'Responsável Comercial', '+55 11 3858-1900', NULL, 'calcados_varejo', 'morno', 'Calçados SP | Fornecedor de equipamentos de segurança | Freguesia do Ó, São Paulo | 4.6⭐'),
  ('SR Fabrica de Moveis', 'Responsável Comercial', '+55 11 3966-1020', NULL, 'calcados_varejo', 'morno', 'Calçados SP | Moveleiro | Casa Verde, São Paulo | 4.8⭐'),
  ('Line Duarte - Loja de Fábrica - Atacado e Varejo', 'Responsável Comercial', '+55 11 96942-1576', NULL, 'calcados_varejo', 'morno', 'Calçados SP | Loja de calçado | Jardim Sao Francisco (Zona Leste), São Paulo | 5⭐'),
  ('São Paulo Distribuidora', 'Responsável Comercial', '+55 11 2798-1000', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Distribuidor de papel | Cidade Patriarca, São Paulo | 4.8⭐'),
  ('Calçados Zapata - Atacado Cav.303', 'Responsável Comercial', '+55 11 2292-3700', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Brás, São Paulo | 4.2⭐'),
  ('Santo Cristo Distribuidora de Cimento', 'Responsável Comercial', '+55 11 2052-8000', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de materiais de construção | Jardim Sao Sebastiao, São Paulo | 4.3⭐'),
  ('Fabiola Pezzi Atacado', 'Responsável Comercial', '+55 11 94476-7097', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Brás, São Paulo | 4.3⭐'),
  ('J Almeida Distribuidora de C. Enlatados e Sucos', 'Responsável Comercial', '', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Serviço de distribuição | Jardim das Pedras, São Paulo | 4.5⭐'),
  ('Fonte Azul Distribuidora de Água e Acessórios', 'Responsável Comercial', '+55 11 2651-8009', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Distribuidor de bebidas | Vila Matilde, São Paulo | 4.2⭐'),
  ('Dagamí Industrial Calçados Ltda', 'Responsável Comercial', '+55 11 95665-5913', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Jardim Brasil, São Paulo | 4.8⭐'),
  ('Loja CMC - Atacado e Varejo de E.P.I | Calçados de Segurança e Acessórios para Motociclistas', 'Responsável Comercial', '+55 11 97615-6831', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Vila Tolstoi, São Paulo | 4.5⭐'),
  ('AX DISTRIBUIDORA', 'Responsável Comercial', '+55 11 96195-0520', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de roupas para bebês | Brás, São Paulo | 4.5⭐'),
  ('Global Calçados Atacado & Varejo', 'Responsável Comercial', '+55 11 2291-8671', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Brás, São Paulo | 4.9⭐'),
  ('Best Shoes Tênis Primeira Linha Premium Atacado e Varejo', 'Responsável Comercial', '+55 11 97689-5493', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Atacadista de calçados | Brás, São Paulo | 5⭐'),
  ('Muzzot''y', 'Responsável Comercial', '+55 11 93748-1456', NULL, 'calcados_industria', 'frio', 'Calçados SP | Fabricante | Chácara São Silvestre, São Paulo | 5⭐'),
  ('Fabrica de Chinelos Bom de Pé', 'Responsável Comercial', '+55 11 98895-7808', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Freguesia do Ó, São Paulo | 3.9⭐'),
  ('Maropo Comércio de Calçados (Somente Atacado)', 'Responsável Comercial', '+55 11 99476-3130', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Brás, São Paulo | 4.8⭐'),
  ('Kara D´Santa Distribuidora de Calçados', 'Responsável Comercial', '+55 11 97693-9797', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Atacadista | Ipiranga, São Paulo | 5⭐'),
  ('Loja D''Fabrica', 'Responsável Comercial', '+55 11 94773-6259', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de Roupa | Parelheiros, São Paulo | 3⭐'),
  ('Footstation - Sapatilhas Atacado e Varejo', 'Responsável Comercial', '+55 11 2618-3191', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Pari, São Paulo | 5⭐'),
  ('Formaleste Indústria e Comércio de Formas para Calçados', 'Responsável Comercial', '+55 11 2958-0386', NULL, 'calcados_industria', 'frio', 'Calçados SP | Empresa de fabricação de plástico | Vila Ré, São Paulo | 5⭐'),
  ('Malu Calçados Atacado', 'Responsável Comercial', '+55 11 95299-2273', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Santo Amaro, São Paulo | 3.5⭐'),
  ('Alta Indústria de Trançados', 'Responsável Comercial', '+55 11 2618-2203', NULL, 'calcados_industria', 'frio', 'Calçados SP | Fabricante | Belenzinho, São Paulo | 3⭐'),
  ('Prados Atacado de Sapatos – Fábrica de Sapatos e Calçados em São Paulo', 'Responsável Comercial', '+55 11 94746-8778', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Guaianases, São Paulo | 5⭐'),
  ('Compra Certa Atacado', 'Responsável Comercial', '+55 11 3327-3327', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Atacadista de calçados | Brás, São Paulo | 5⭐'),
  ('SKG Calçados / Di Santinni - ATACADO', 'Responsável Comercial', '+55 11 91563-1986', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Brás, São Paulo | 4.7⭐'),
  ('Nova Serrana Record Fábrica De Sapatos', 'Responsável Comercial', '', NULL, 'calcados_industria', 'frio', 'Calçados SP | Fabricante | Jardim Record, São Paulo | 4⭐'),
  ('Dalva Chinelos Atacado e Varejo', 'Responsável Comercial', '+55 11 96259-8826', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Brás, São Paulo | 5⭐'),
  ('gaduda distribuidor de calçados havaianas', 'Responsável Comercial', '', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Brás, São Paulo | 5⭐'),
  ('Rose Atacado', 'Responsável Comercial', '+55 11 97687-3165', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Atacadista de calçados | Brás, São Paulo | 3⭐'),
  ('Soleva Calçados Atacado', 'Responsável Comercial', '+55 11 96727-3222', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Atacadista de calçados | Brás, São Paulo | 5⭐'),
  ('DuoBag Acessórios', 'Responsável Comercial', '+55 11 98275-6498', NULL, 'calcados_industria', 'frio', 'Calçados SP | Fabricante | Jardim Angela, São Paulo | 5⭐'),
  ('Youz Atacado', 'Responsável Comercial', '+55 11 91151-8744', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Atacadista de calçados | Jardim Francisco Mendes, São Paulo'),
  ('Atacado Calçados - Chico Distribuidora', 'Responsável Comercial', '+55 11 94854-8613', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Brás, São Paulo'),
  ('Maktub Distribuidora de Fraldas e Calçados', 'Responsável Comercial', '+55 11 2081-4747', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Atacadista | Pari, São Paulo'),
  ('ATC Brás Tênis 1° Linha Atacado e Varejo', 'Responsável Comercial', '+55 11 98674-5086', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Brás, São Paulo'),
  ('ralicia calçados atacado e varejo', 'Responsável Comercial', '+55 11 2694-0066', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Brás, São Paulo'),
  ('AL.Atacado', 'Responsável Comercial', '+55 11 98306-9839', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Brás, São Paulo'),
  ('DBIZ II Fabricação e Venda de Calçados Ltda.', 'Responsável Comercial', '+55 11 96031-0646', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Vila Ré, São Paulo'),
  ('Oscar Calcados (180 lojas)', 'Responsável Comercial', '+55 (11) 5039-9748', NULL, 'calcados_rede', 'quente', 'Calçados SP | Rede de Lojas | , Sao Paulo / Grande SP'),
  ('Mundial Calcados', 'Responsável Comercial', '(11) 97788-5000', NULL, 'calcados_rede', 'quente', 'Calçados SP | Rede de Lojas | , Sao Paulo / Grande SP'),
  ('Pontal Calcados', 'Responsável Comercial', '0800 172 355', 'sac@pontal.com.br', 'calcados_rede', 'quente', 'Calçados SP | Rede de Lojas | , Sao Paulo / Grande SP | 4.3⭐'),
  ('Di Gaspi', 'Responsável Comercial', '(11) 5501-8400', 'atendimento@digaspi.com.br', 'calcados_rede', 'quente', 'Calçados SP | Rede de Lojas | , Sao Paulo / Grande SP | 4.1⭐'),
  ('Spot Shoes', 'Responsável Comercial', '(11) 3362-0116', NULL, 'calcados_rede', 'quente', 'Calçados SP | Rede de Lojas | , Sao Paulo / Grande SP'),
  ('Artwalk', 'Responsável Comercial', '', NULL, 'calcados_rede', 'quente', 'Calçados SP | Rede de Lojas (Sneakers) | , Sao Paulo / Grande SP'),
  ('Romao Calcados', 'Responsável Comercial', '', NULL, 'calcados_rede', 'quente', 'Calçados SP | Rede de Lojas | , Sao Paulo / Grande SP'),
  ('Calcados Bibi', 'Responsável Comercial', '+55 11 4305-9457', NULL, 'calcados_rede', 'quente', 'Calçados SP | Franquia/Rede | , Sao Paulo / Grande SP | 5⭐'),
  ('Carmen Steffens', 'Responsável Comercial', '', NULL, 'calcados_rede', 'quente', 'Calçados SP | Franquia | , Sao Paulo / Grande SP'),
  ('Pampili', 'Responsável Comercial', '', NULL, 'calcados_rede', 'quente', 'Calçados SP | Franquia Infantil | , Sao Paulo / Grande SP'),
  ('Santa Lolla', 'Responsável Comercial', '', NULL, 'calcados_rede', 'quente', 'Calçados SP | Franquia | , Sao Paulo / Grande SP'),
  ('Sandaliaria', 'Responsável Comercial', '', NULL, 'calcados_rede', 'quente', 'Calçados SP | Franquia | , Sao Paulo / Grande SP'),
  ('Lojas Pompeia', 'Responsável Comercial', '', NULL, 'calcados_rede', 'quente', 'Calçados SP | Rede de Lojas | , Sao Paulo / Grande SP'),
  ('ZZ Mall', 'Responsável Comercial', '', NULL, 'calcados_rede', 'quente', 'Calçados SP | Rede de Lojas | , Sao Paulo / Grande SP'),
  ('Gabriella Calcados', 'Responsável Comercial', '(11) 3197-2270', 'atendimento@gabriellacalcados.com.br', 'calcados_rede', 'quente', 'Calçados SP | Rede de Lojas | , Sao Paulo / Grande SP'),
  ('Angela Calcados', 'Responsável Comercial', '(11) 2284-6700', NULL, 'calcados_rede', 'quente', 'Calçados SP | Rede de Lojas | , Sao Paulo / Grande SP'),
  ('Kallan', 'Responsável Comercial', '(11) 91036-7002', 'sac@kallan.com.br', 'calcados_rede', 'quente', 'Calçados SP | Rede de Lojas | , Sao Paulo / Grande SP'),
  ('Avacy Distribuidora de Calcados', 'Responsável Comercial', '', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Distribuidora | , Sao Paulo / Grande SP'),
  ('Wilson Atacado de Calcados', 'Responsável Comercial', '', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Atacado | , Sao Paulo / Grande SP'),
  ('Daniel Atacado (Grendene)', 'Responsável Comercial', '', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Atacado | , Sao Paulo / Grande SP'),
  ('CECI Calcados', 'Responsável Comercial', '', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Atacado | , Sao Paulo / Grande SP'),
  ('Zapata Atacado', 'Responsável Comercial', '', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Atacado | , Sao Paulo / Grande SP'),
  ('CooperShoes', 'Responsável Comercial', '', NULL, 'calcados_industria', 'frio', 'Calçados SP | Fabrica | , Sao Paulo / Grande SP'),
  ('Bompel Industria de Calcados', 'Responsável Comercial', '', NULL, 'calcados_industria', 'frio', 'Calçados SP | Fabrica | , Sao Paulo / Grande SP'),
  ('Calcados Beira Rio', 'Responsável Comercial', '', NULL, 'calcados_industria', 'frio', 'Calçados SP | Fabrica | , Sao Paulo / Grande SP'),
  ('Pegada Calcados', 'Responsável Comercial', '', NULL, 'calcados_industria', 'frio', 'Calçados SP | Fabrica | , Sao Paulo / Grande SP'),
  ('WestCoast', 'Responsável Comercial', '', NULL, 'calcados_industria', 'frio', 'Calçados SP | Fabrica | , Sao Paulo / Grande SP'),
  ('Ricaplast Industria de Calcados', 'Responsável Comercial', '', NULL, 'calcados_industria', 'frio', 'Calçados SP | Fabrica | , Sao Paulo / Grande SP'),
  ('Oba Calcados (Fabrica Feminina)', 'Responsável Comercial', '', NULL, 'calcados_industria', 'frio', 'Calçados SP | Fabrica | , Sao Paulo / Grande SP'),
  ('Calcados Mac', 'Responsável Comercial', '', NULL, 'calcados_industria', 'frio', 'Calçados SP | Fabricante | , Sao Paulo / Grande SP'),
  ('Difranca Calcados', 'Responsável Comercial', '', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Distribuidora | , Sao Paulo / Grande SP'),
  ('Piccadilly', 'Responsável Comercial', '', NULL, 'calcados_rede', 'quente', 'Calçados SP | Franquia/Fabrica | , Sao Paulo / Grande SP'),
  ('Samello', 'Responsável Comercial', '', NULL, 'calcados_rede', 'quente', 'Calçados SP | Franquia | , Sao Paulo / Grande SP'),
  ('New Shoes', 'Responsável Comercial', '', NULL, 'calcados_rede', 'quente', 'Calçados SP | Franquia | , Sao Paulo / Grande SP'),
  ('Outer Shoes', 'Responsável Comercial', '', NULL, 'calcados_rede', 'quente', 'Calçados SP | Franquia | , Sao Paulo / Grande SP'),
  ('Sergios Calcados', 'Responsável Comercial', '', NULL, 'calcados_rede', 'quente', 'Calçados SP | Franquia | , Sao Paulo / Grande SP'),
  ('KidStok', 'Responsável Comercial', '', NULL, 'calcados_rede', 'quente', 'Calçados SP | Franquia Infantil | , Sao Paulo / Grande SP'),
  ('Clovis Calcados', 'Responsável Comercial', '', NULL, 'calcados_rede', 'quente', 'Calçados SP | Rede de Lojas | , Sao Paulo / Grande SP'),
  ('Anita Shoes', 'Responsável Comercial', '', NULL, 'calcados_rede', 'quente', 'Calçados SP | Rede de Lojas | , Sao Paulo / Grande SP'),
  ('Grupo Dass (Fila, Umbro)', 'Responsável Comercial', '', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Grupo Industrial | , Sao Paulo / Grande SP'),
  ('Zapata Calcados', 'Responsável Comercial', '', NULL, 'calcados_rede', 'quente', 'Calçados SP | Rede de Lojas | , Sao Paulo / Grande SP'),
  ('Domidona Atacado', 'Responsável Comercial', '', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Atacado | , Sao Paulo / Grande SP'),
  ('Milano Calcados Atacado', 'Responsável Comercial', '', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Atacado | , Sao Paulo / Grande SP'),
  ('Dolce Store Atacado', 'Responsável Comercial', '', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Atacado | , Sao Paulo / Grande SP'),
  ('Assaí Atacadista', 'Responsável Comercial', '+55 11 5970-5900', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Atacadista | Cidade Dutra, São Paulo | 4.2⭐'),
  ('ROMÃO CALÇADOS', 'Responsável Comercial', '+55 11 2293-0713', NULL, 'calcados_varejo', 'morno', 'Calçados SP | Loja de calçado | Cidade Mãe do Céu, São Paulo | 4.5⭐'),
  ('Calçados Paraná', 'Responsável Comercial', '+55 11 2693-0811', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Brás, São Paulo | 4.3⭐'),
  ('Durval Calçados Finos', 'Responsável Comercial', '+55 11 3311-7061', NULL, 'calcados_varejo', 'quente', 'Calçados SP | Loja de calçado | Luz, São Paulo | 4.9⭐'),
  ('Eurico Calçados Moema', 'Responsável Comercial', '+55 11 5054-8877', NULL, 'calcados_varejo', 'quente', 'Calçados SP | Loja de calçado | Moema, São Paulo | 4.7⭐'),
  ('Capezio do Brasil', 'Responsável Comercial', '+55 11 96912-0423', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de artigos para dança | Ipiranga, São Paulo | 4.3⭐'),
  ('Laranja Lima Shoes', 'Responsável Comercial', '+55 11 2067-8100', NULL, 'calcados_varejo', 'morno', 'Calçados SP | Loja de calçado | Ipiranga, São Paulo | 4.6⭐'),
  ('Mundial Calçados', 'Responsável Comercial', '+55 11 2796-5225', NULL, 'calcados_varejo', 'morno', 'Calçados SP | Loja de calçado | Brás, São Paulo | 4.5⭐'),
  ('PLB Importadora', 'Responsável Comercial', '+55 11 91653-3436', NULL, 'calcados_varejo', 'quente', 'Calçados SP | Importadora | Luz, São Paulo | 4.8⭐'),
  ('Pontal', 'Responsável Comercial', '+55 11 2040-3801', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Itaquera, São Paulo | 4.3⭐'),
  ('Jennifer Hellen Calçados', 'Responsável Comercial', '+55 11 2574-5180', NULL, 'calcados_varejo', 'morno', 'Calçados SP | Loja de calçado | Vila Ré, São Paulo | 4.6⭐'),
  ('Guadalupe Store', 'Responsável Comercial', '+55 11 93312-0852', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Bom Retiro, São Paulo | 4.3⭐'),
  ('Taka Taka Calçados', 'Responsável Comercial', '+55 11 2983-5677', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Vila Sabrina, São Paulo | 4.4⭐'),
  ('O Mundo das Sapatilhas', 'Responsável Comercial', '+55 11 3476-0768', NULL, 'calcados_varejo', 'morno', 'Calçados SP | Loja de calçado | Freguesia do Ó, São Paulo | 4.6⭐'),
  ('Ana Mello Calçados', 'Responsável Comercial', '+55 11 2206-0052', NULL, 'calcados_varejo', 'morno', 'Calçados SP | Loja de calçado | Jardim Franca, São Paulo | 4.6⭐'),
  ('Gabriela Calçados - Penha', 'Responsável Comercial', '+55 11 3197-2273', NULL, 'calcados_varejo', 'morno', 'Calçados SP | Loja de calçado | Penha de França, São Paulo | 4.6⭐'),
  ('Alpargatas S.A.', 'Responsável Comercial', '+55 11 3847-7322', NULL, 'calcados_varejo', 'morno', 'Calçados SP | Escritório da empresa | Vila Gertrudes, São Paulo | 4.5⭐'),
  ('Fábrica de Tênis', 'Responsável Comercial', '+55 11 98142-2218', NULL, 'calcados_varejo', 'morno', 'Calçados SP | Fábrica de Calçados | Santana, São Paulo | 4.9⭐'),
  ('Alfredo Calçados', 'Responsável Comercial', '+55 11 2954-3081', NULL, 'calcados_varejo', 'morno', 'Calçados SP | Loja de calçado | Vila Maria Alta, São Paulo | 4.7⭐'),
  ('Week Shoes | Sapato Feminino', 'Responsável Comercial', '+55 11 94933-2516', NULL, 'calcados_varejo', 'morno', 'Calçados SP | Loja de calçado | Artur Alvim, São Paulo | 5⭐'),
  ('Senhorella Calçados', 'Responsável Comercial', '+55 11 2017-6443', NULL, 'calcados_varejo', 'morno', 'Calçados SP | Loja de calçado | Cidade São Mateus, São Paulo | 4.9⭐'),
  ('Becker Calçados', 'Responsável Comercial', '+55 11 2955-5934', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Vila Maria, São Paulo | 4.4⭐'),
  ('Poupaki Atacadista - Cidade Dutra', 'Responsável Comercial', '+55 11 2036-4100', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Atacadista | Parque Alto do Rio Bonito, São Paulo | 4⭐'),
  ('Esperança Calçados Show - Unidade São Miguel 01', 'Responsável Comercial', '+55 11 91541-7708', NULL, 'calcados_varejo', 'morno', 'Calçados SP | Loja de calçado | São Miguel Paulista, São Paulo | 4.7⭐'),
  ('Arthur Calçados', 'Responsável Comercial', '+55 11 2957-7268', NULL, 'calcados_varejo', 'morno', 'Calçados SP | Loja de calçado | Vila Ré, São Paulo | 4.6⭐'),
  ('Pé Vermelho Calçados', 'Responsável Comercial', '+55 11 3333-3865', NULL, 'calcados_varejo', 'morno', 'Calçados SP | Loja de calçado | Bom Retiro, São Paulo | 4.5⭐'),
  ('Jennifer Hellen Calçados Brás', 'Responsável Comercial', '+55 11 93463-7183', NULL, 'calcados_varejo', 'morno', 'Calçados SP | Loja de calçado | Brás, São Paulo | 4.8⭐'),
  ('Débora Calçados', 'Responsável Comercial', '+55 11 91669-5765', NULL, 'calcados_varejo', 'morno', 'Calçados SP | Loja de calçado | Jardim da Saúde, São Paulo | 4.7⭐'),
  ('São Roque Atacadista de Calçados', 'Responsável Comercial', '+55 11 2694-1055', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Brás, São Paulo | 4.4⭐'),
  ('A Mafalda Sapatos', 'Responsável Comercial', '+55 11 2338-5762', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Pinheiros, São Paulo | 4.4⭐'),
  ('Primo Outlet Brás - Calçados, cintos e carteiras', 'Responsável Comercial', '+55 11 97370-3034', NULL, 'calcados_varejo', 'morno', 'Calçados SP | Loja de calçado | Brás, São Paulo | 4.9⭐'),
  ('Só Mais Um Shoes', 'Responsável Comercial', '+55 11 2659-2498', NULL, 'calcados_varejo', 'morno', 'Calçados SP | Loja de calçado | Penha de França, São Paulo | 5⭐'),
  ('Sempre Divina', 'Responsável Comercial', '+55 11 97058-8599', NULL, 'calcados_varejo', 'morno', 'Calçados SP | Loja de calçado | Vila Regente Feijó, São Paulo | 4.8⭐'),
  ('Vallentina Calçados', 'Responsável Comercial', '+55 11 99486-5333', NULL, 'calcados_varejo', 'morno', 'Calçados SP | Loja de calçado | Brás, São Paulo | 4.6⭐'),
  ('Fabi Calçados', 'Responsável Comercial', '+55 11 2018-0236', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Parque Sao Rafael, São Paulo | 4.7⭐'),
  ('Estrela Lojas', 'Responsável Comercial', '+55 11 99323-9065', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de Roupa | Parelheiros, São Paulo | 4.2⭐'),
  ('Primus Calçados', 'Responsável Comercial', '+55 11 99316-4567', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Penha de França, São Paulo | 4.3⭐'),
  ('Empório Das Sapatilhas', 'Responsável Comercial', '+55 11 3331-9356', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Bom Retiro, São Paulo | 4.5⭐'),
  ('Lasenna Sapatos Femininos, Bolsas e Acessórios', 'Responsável Comercial', '+55 11 99294-5741', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Jardim Bonfiglioli, São Paulo | 4.9⭐'),
  ('Cacielli Calçados Femininos Tamanhos Grandes - BRÁS', 'Responsável Comercial', '+55 11 98255-7287', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Brás, São Paulo | 4.7⭐'),
  ('Art em Pé', 'Responsável Comercial', '+55 11 99999-6979', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Bom Retiro, São Paulo | 4.3⭐'),
  ('Daniel Calçados - Grendene', 'Responsável Comercial', '+55 11 2696-3160', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Atacadista | Brás, São Paulo | 4.8⭐'),
  ('Mil E Uma Sapatilhas sao miguel paulista', 'Responsável Comercial', '', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | São Miguel Paulista, São Paulo | 4.2⭐'),
  ('Esperança Calçados', 'Responsável Comercial', '+55 11 2206-6679', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Jaçanã, São Paulo | 4.4⭐'),
  ('00 Fábrica de Tênis - Brás', 'Responsável Comercial', '+55 11 97447-2047', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Brás, São Paulo | 4.4⭐'),
  ('MIB comércio de ferramentas e abrasivos', 'Responsável Comercial', '+55 11 2013-0096', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de ferramentas | Jardim Sapopemba, São Paulo | 4.7⭐'),
  ('Dolce & Menta Calçados', 'Responsável Comercial', '+55 11 94024-8083', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Tatuapé, São Paulo | 4.6⭐'),
  ('CALÇADOS DE FRANCA E CIA', 'Responsável Comercial', '+55 11 3723-3900', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Butantã, São Paulo | 4.4⭐'),
  ('Keron sapatilhas', 'Responsável Comercial', '+55 11 98252-0154', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Santo Amaro, São Paulo | 4.5⭐'),
  ('Sapataria AGP 1', 'Responsável Comercial', '+55 11 5514-4100', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Sapateiro | Parque Santo Antônio, São Paulo | 4.8⭐'),
  ('MAP Calçados', 'Responsável Comercial', '+55 11 2698-5758', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Brás, São Paulo | 4.7⭐'),
  ('Deka Calçados', 'Responsável Comercial', '+55 11 2944-6944', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Itaquera, São Paulo | 4.3⭐'),
  ('Indústria de Calçados Beira Rio', 'Responsável Comercial', '+55 11 2651-2566', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Vila Matilde, São Paulo | 4.5⭐'),
  ('Usaflex', 'Responsável Comercial', '+55 11 91184-6160', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Itaquera, São Paulo | 4.6⭐'),
  ('Gigi Calçados', 'Responsável Comercial', '+55 11 5925-6897', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Vila Sao Jose (Cidade Dutra), São Paulo | 4.5⭐'),
  ('Du Calçados', 'Responsável Comercial', '+55 11 94299-2573', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Brás, São Paulo | 5⭐'),
  ('Cris Scarpe - Jack Calçados', 'Responsável Comercial', '+55 11 97414-2273', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Brás, São Paulo | 4.5⭐'),
  ('Casa Dos Chinelos', 'Responsável Comercial', '+55 11 99981-8524', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Brás, São Paulo | 4.4⭐'),
  ('DAYLY CALÇADOS', 'Responsável Comercial', '+55 11 2514-2411', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Guaianases, São Paulo | 4.9⭐'),
  ('PORTO Calçados', 'Responsável Comercial', '+55 11 96127-0891', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Brás, São Paulo | 4.8⭐'),
  ('AC Atacadista', 'Responsável Comercial', '+55 11 99927-1111', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Atacadista | Jardim Kioto, São Paulo | 5⭐'),
  ('São Francisco Calçados', 'Responsável Comercial', '+55 11 2943-1290', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Jardim Belem, São Paulo | 4.7⭐'),
  ('Carlos Calçados', 'Responsável Comercial', '+55 11 2987-1031', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Vila Sabrina, São Paulo | 4.1⭐'),
  ('Bela Dany Calçados e Acessórios', 'Responsável Comercial', '+55 11 96080-6296', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Jardim Belem, São Paulo | 5⭐'),
  ('Ksouza - Manequins de Plásticos e Acessórios', 'Responsável Comercial', '+55 11 93225-8266', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de manequins | Jardim Imperador (Zona Leste), São Paulo | 5⭐'),
  ('HW Comercial', 'Responsável Comercial', '+55 11 3227-9114', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Bom Retiro, São Paulo | 4.4⭐'),
  ('A Toca da Sola', 'Responsável Comercial', '+55 11 3628-1932', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Vila Esperança, São Paulo | 4.2⭐'),
  ('Bella Shoes', 'Responsável Comercial', '+55 11 2283-0690', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Santana, São Paulo | 4.8⭐'),
  ('Sutil Calçados', 'Responsável Comercial', '+55 11 99918-6418', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Vila Gomes Cardim, São Paulo | 4.9⭐'),
  ('Momentshoes Rasteirinhas Personalizadas', 'Responsável Comercial', '+55 11 91093-9620', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Chácara Mafalda, São Paulo | 5⭐'),
  ('GLAC Calçados Sustentáveis', 'Responsável Comercial', '+55 11 99289-8448', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Chácara Tatuapé, São Paulo | 4.8⭐'),
  ('MM Calçados', 'Responsável Comercial', '+55 11 3107-8811', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Centro Histórico de São Paulo, São Paulo | 4.8⭐'),
  ('Cristiam Mello Calcados', 'Responsável Comercial', '+55 11 99909-4600', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Brás, São Paulo | 5⭐'),
  ('Michelle Calçados Femininos', 'Responsável Comercial', '', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Cidade Antônio Estêvão de Carvalho, São Paulo | 4.8⭐'),
  ('Calçaper Couros', 'Responsável Comercial', '+55 11 3982-9472', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Vila Nova Cachoeirinha, São Paulo | 4.6⭐'),
  ('Sapato nunca é D+', 'Responsável Comercial', '+55 11 97043-9724', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Vila Guilhermina, São Paulo | 5⭐'),
  ('Deu Onda sapatilhas', 'Responsável Comercial', '+55 11 98391-2011', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Luz, São Paulo | 4.8⭐'),
  ('Dally Calçados', 'Responsável Comercial', '+55 11 2541-8211', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Jardim Verônia, São Paulo | 5⭐'),
  ('KT EPI', 'Responsável Comercial', '+55 11 2506-9606', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Atacadista | Cidade Líder, São Paulo | 4.5⭐'),
  ('Plaza B2B - Marketplace Atacadista', 'Responsável Comercial', '+55 11 2698-7183', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Atacadista de calçados | Brás, São Paulo | 4.8⭐'),
  ('Nova Arte Calçados', 'Responsável Comercial', '+55 11 99628-5887', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Vila Maria, São Paulo | 4.8⭐'),
  ('Ana Félix Sapatos Artesanais', 'Responsável Comercial', '+55 11 2741-6847', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Artur Alvim, São Paulo | 4.1⭐'),
  ('Pucci Smokovitz Comércio Calçados', 'Responsável Comercial', '+55 11 2692-5858', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Atacadista | Brás, São Paulo | 3.9⭐'),
  ('Só Chinelos', 'Responsável Comercial', '+55 11 93353-7779', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Vila Maria Alta, São Paulo | 4.5⭐'),
  ('Nill Shoes', 'Responsável Comercial', '+55 11 5926-0175', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja | Jardim São Gonçalo, São Paulo | 4⭐'),
  ('Di Gaspi - Parelheiros', 'Responsável Comercial', '+55 11 5509-3956', 'atendimento@digaspi.com.br', 'calcados_varejo', 'frio', 'Calçados SP | Loja de departamento | Jardim São Gonçalo, São Paulo | 4.1⭐'),
  ('LOJA DE ROUPAS E CALCADOS BENE LTDA', 'Responsável Comercial', '+55 11 5928-7541', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Parque America, São Paulo | 3.3⭐'),
  ('Lojas Atuante', 'Responsável Comercial', '+55 11 5599-6498', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de Roupa | Parelheiros, São Paulo | 3.6⭐'),
  ('D.SANDRINI MODAS', 'Responsável Comercial', '+55 11 97358-1701', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de Roupa | Jardim Novo Horizonte, São Paulo | 4.1⭐'),
  ('Zeferino', 'Responsável Comercial', '+55 11 3152-6090', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Consolação, São Paulo | 4.5⭐'),
  ('D&N FERRAMENTAS HIDRAULICA E ELETRICA', 'Responsável Comercial', '+55 11 5920-8996', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Parelheiros, São Paulo | 4.9⭐'),
  ('GAB Calçados (Loja de Fábrica)', 'Responsável Comercial', '+55 11 96966-5071', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Consolação, São Paulo | 4.6⭐'),
  ('Madame Fulô | Calçados femininos', 'Responsável Comercial', '+55 11 2892-9069', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Jardim São Paulo, São Paulo | 5⭐'),
  ('Mega Shopping', 'Responsável Comercial', '+55 11 97702-9266', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja | Cidade São Mateus, São Paulo | 4.5⭐'),
  ('Mariah Sapatilhas', 'Responsável Comercial', '', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Atacadista | São Mateus, São Paulo | 5⭐'),
  ('Kenfoot Produtos Magnéticos', 'Responsável Comercial', '+55 11 98316-5299', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Belenzinho, São Paulo | 4.6⭐'),
  ('Rogério Calçados', 'Responsável Comercial', '+55 11 2081-0468', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Brás, São Paulo | 4.9⭐'),
  ('Dkcalçados', 'Responsável Comercial', '+55 11 94773-2648', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | São Mateus, São Paulo | 3.9⭐'),
  ('Sindicato Trabalhadores Indústria Calçados São Paulo', 'Responsável Comercial', '+55 11 3345-0100', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Sindicato | Cambuci, São Paulo | 2.5⭐'),
  ('AnaB Fábrica de calçados', 'Responsável Comercial', '+55 11 93395-0161', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Vila Matilde, São Paulo | 4.1⭐'),
  ('Calçados But''s', 'Responsável Comercial', '+55 11 2746-9931', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Parque Artur Alvim, São Paulo | 3.7⭐'),
  ('Júlia Jaques calçados', 'Responsável Comercial', '+55 11 95275-6162', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Lauzane Paulista, São Paulo | 4.9⭐'),
  ('D+ Sapatos', 'Responsável Comercial', '+55 11 97967-7931', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Brás, São Paulo | 4.1⭐'),
  ('Mil Pares', 'Responsável Comercial', '+55 11 99288-4818', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Ipiranga, São Paulo | 4.5⭐'),
  ('Marcas e Pegadas', 'Responsável Comercial', '+55 11 93046-9689', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Parelheiros, São Paulo | 5⭐'),
  ('Juju Shoes indústria e comércio de calçados Ltda', 'Responsável Comercial', '+55 11 96286-9829', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Vila matilde, São Paulo | 5⭐'),
  ('Alpargateria Cervera (Fábrica)', 'Responsável Comercial', '+55 11 5543-5000', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Vila Santa Catarina, São Paulo | 4.3⭐'),
  ('LX LUXUOSA', 'Responsável Comercial', '+55 11 2694-3156', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Brás, São Paulo | 5⭐'),
  ('M3G CALÇADOS', 'Responsável Comercial', '+55 11 98838-1761', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Freguesia do Ó, São Paulo | 4⭐'),
  ('Fábrica Calçados Giene', 'Responsável Comercial', '+55 11 2641-2839', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Penha de França, São Paulo | 2.3⭐'),
  ('Indústria Comércio Calçados Acarie', 'Responsável Comercial', '+55 11 2291-0406', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Brás, São Paulo | 5⭐'),
  ('Calçados Yellow', 'Responsável Comercial', '+55 11 2280-4967', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Burgo Paulista, São Paulo | 4.3⭐'),
  ('Lumina Calçados', 'Responsável Comercial', '+55 11 95381-2457', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Brás, São Paulo | 4.3⭐'),
  ('Leoppe Indústria e Comércio de Calçados', 'Responsável Comercial', '+55 11 2331-5367', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Jardim Maria Estela, São Paulo | 4.7⭐'),
  ('Kennon Shoes Indústria Comércio Calçados', 'Responsável Comercial', '+55 11 4212-5172', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de roupas de designer | Parque Paulistano, São Paulo | 4⭐'),
  ('A PREDILETA CALÇADOS Ltda', 'Responsável Comercial', '+55 11 5920-8738', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja | Parelheiros, São Paulo | 5⭐'),
  ('Granata Indústria e Comércio', 'Responsável Comercial', '+55 11 2721-2675', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Aricanduva, São Paulo | 4⭐'),
  ('DOMP Calçados', 'Responsável Comercial', '+55 11 2292-6961', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Brás, São Paulo | 4.8⭐'),
  ('Yvate Calçados', 'Responsável Comercial', '+55 11 2291-1784', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Atacadista | Brás, São Paulo | 4.2⭐'),
  ('Revendedora Beira Rio Conforto, Moleca e Vizzano', 'Responsável Comercial', '+55 11 94857-5564', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Santana, São Paulo | 4.2⭐'),
  ('Diplomata Calçados', 'Responsável Comercial', '+55 11 3311-9768', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Centro Histórico de São Paulo, São Paulo | 4.8⭐'),
  ('São Paulo Calçados', 'Responsável Comercial', '+55 11 93467-7293', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Vila Lucia, São Paulo | 5⭐'),
  ('ADEGA XEQUE MATE - PARELHEIROS', 'Responsável Comercial', '+55 11 97528-3155', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fornecedor de bebidas | Jardim Progresso Parelheiros, São Paulo | 5⭐'),
  ('Tereza Calçados', 'Responsável Comercial', '+55 11 2291-0965', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Brás, São Paulo | 4⭐'),
  ('MCZ Calçados', 'Responsável Comercial', '+55 11 94701-4686', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Tatuapé, São Paulo | 5⭐'),
  ('Representante Comercial Dakota e Tanara', 'Responsável Comercial', '+55 11 2901-3049', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Vila Guilherme, São Paulo | 4⭐'),
  ('Top Calçados', 'Responsável Comercial', '+55 11 99947-0757', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Brás, São Paulo | 5⭐'),
  ('DUBLACONFORT COMPONENTES P CALÇADOS LTDA', 'Responsável Comercial', '+55 11 94733-2812', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica têxtil | Vila Guilherme, São Paulo | 5⭐'),
  ('Chilli''s Calçados', 'Responsável Comercial', '+55 11 5921-1848', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Parelheiros, São Paulo | 5⭐'),
  ('B Indústrias de Calçados', 'Responsável Comercial', '+55 11 2695-0878', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Belenzinho, São Paulo | 5⭐'),
  ('SEA SUMMER PLACAS', 'Responsável Comercial', '+55 11 98565-1515', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Vila Maria, São Paulo | 3⭐'),
  ('Bortex Calçados Componentes', 'Responsável Comercial', '+55 11 2943-6777', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Parque Boturussu, São Paulo | 5⭐'),
  ('Smart Shoes', 'Responsável Comercial', '+55 11 99102-6342', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Santa Teresinha, São Paulo | 3.7⭐'),
  ('Indústria Comércio Calçados Três B', 'Responsável Comercial', '+55 11 2280-4974', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Vila Uniao (Zona Leste), São Paulo | 3.7⭐'),
  ('SK Comércio de Máquinas para Calçados', 'Responsável Comercial', '+55 11 3227-4453', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Brás, São Paulo | 5⭐'),
  ('Globo Crayon Chinelos Magnéticos', 'Responsável Comercial', '+55 11 96012-8778', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Vila Brasilio Machado, São Paulo | 5⭐'),
  ('Simoni Calçados', 'Responsável Comercial', '+55 11 96416-4219', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Jardim Popular, São Paulo | 3.5⭐'),
  ('Via Bag', 'Responsável Comercial', '+55 11 2684-1959', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Vila Ré, São Paulo | 5⭐'),
  ('KAKA EMPÓRIOO', 'Responsável Comercial', '+55 11 95667-7528', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Jardim Eliane, São Paulo | 5⭐'),
  ('Estação Calçados', 'Responsável Comercial', '+55 11 91350-0373', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Parque Paulistano, São Paulo | 5⭐'),
  ('Vi Shopcalçados', 'Responsável Comercial', '+55 11 96361-0922', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Itaquera, São Paulo | 5⭐'),
  ('Compra Certa Comércio de Calçados', 'Responsável Comercial', '+55 11 2618-2730', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Brás, São Paulo | 4.5⭐'),
  ('ALPARGATAS SP', 'Responsável Comercial', '+55 11 99664-5551', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Atacadista de calçados | Brás, São Paulo | 5⭐'),
  ('Nina Calçados', 'Responsável Comercial', '+55 11 2292-2807', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Brás, São Paulo | 4.5⭐'),
  ('Rei dos Chinelos', 'Responsável Comercial', '+55 11 97704-3638', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Brás, São Paulo | 3⭐'),
  ('VZT Indústria e Comércio de Calçados', 'Responsável Comercial', '+55 11 2268-2508', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Tatuapé, São Paulo | 4.5⭐'),
  ('Maktub Store', 'Responsável Comercial', '+55 11 96616-1953', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Jardim da Conquista, São Paulo | 5⭐'),
  ('Shine One Renovação Calçados Roupas Ltda Ep', 'Responsável Comercial', '+55 11 5181-1060', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Chácara Santo Antônio (Zona Sul), São Paulo | 3⭐'),
  ('Buiu CALÇADOS', 'Responsável Comercial', '', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Parelheiros, São Paulo | 4⭐'),
  ('4B Calçados', 'Responsável Comercial', '+55 11 5921-5267', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Colônia (Zona Sul), São Paulo | 5⭐'),
  ('Anny Shoes', 'Responsável Comercial', '+55 11 96514-2885', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Vila Maria Alta, São Paulo | 5⭐'),
  ('Love Company Calçados', 'Responsável Comercial', '+55 11 2925-4506', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Vila Ré, São Paulo | 5⭐'),
  ('Outlet Calçados', 'Responsável Comercial', '+55 11 95152-9328', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Jardim Fontalis, São Paulo | 5⭐'),
  ('Sou Eu Sandalias Babuche', 'Responsável Comercial', '+55 11 95080-1975', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Atacadista de calçados | Brás, São Paulo | 5⭐'),
  ('delcol calcados', 'Responsável Comercial', '+55 11 99658-8888', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Brás, São Paulo | 1⭐'),
  ('Plslippers', 'Responsável Comercial', '+55 11 95660-7029', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Limoeiro, São Paulo | 5⭐'),
  ('Outlet dos calçados', 'Responsável Comercial', '', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Sé, São Paulo | 5⭐'),
  ('LALACHINELOS', 'Responsável Comercial', '+55 11 95397-9105', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Subprefeitura de Ermelino Matarazzo, São Paulo | 5⭐'),
  ('Renato calçados', 'Responsável Comercial', '+55 11 2618-5245', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Brás, São Paulo | 5⭐'),
  ('Tênis e sandálias infantil', 'Responsável Comercial', '+55 11 99347-9332', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Vila Yolanda, São Paulo | 5⭐'),
  ('Sandalli Rasteirinhas', 'Responsável Comercial', '+55 11 98056-1305', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Jardim Brasilia, São Paulo | 5⭐'),
  ('ZF Indústria e Comércio de Calçados e Acessórios', 'Responsável Comercial', '+55 11 3846-5584', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Pinheiros, São Paulo | 2⭐'),
  ('Rafa Calcados E Confeccóes', 'Responsável Comercial', '', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Paraíso, São Paulo | 1⭐'),
  ('J e C Chinelos e acessórios', 'Responsável Comercial', '+55 11 3197-3035', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Guaianases, São Paulo | 5⭐'),
  ('Pellegrini® Sapatos Sob-Medida', 'Responsável Comercial', '+55 11 3666-7935', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Água Branca, São Paulo | 5⭐'),
  ('FSL Indústria e Comércio de Brindes e Acessórios Gráficos', 'Responsável Comercial', '+55 11 3872-0536', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de roupas de designer | Vila Romana, São Paulo | 5⭐'),
  ('Betelli Indústria Comércio Calçados', 'Responsável Comercial', '+55 11 5052-5897', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Moema, São Paulo | 1⭐'),
  ('Gigi Marri', 'Responsável Comercial', '', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Santana, São Paulo | 5⭐'),
  ('Apredileta calçados', 'Responsável Comercial', '', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Colônia (Zona Sul), São Paulo'),
  ('Atenas Indústria Comércio Calçados', 'Responsável Comercial', '+55 11 2910-4411', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Vila Macedopolis, São Paulo'),
  ('Mary&M Calçados', 'Responsável Comercial', '+55 11 95648-2865', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | , Sao Paulo'),
  ('Impera Fábrica de Calçados', 'Responsável Comercial', '+55 11 2207-1217', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Jardim Andarai, São Paulo'),
  ('General calçados', 'Responsável Comercial', '+55 11 96726-9965', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Atacadista de calçados | Centro Histórico de São Paulo, São Paulo'),
  ('Susana Calçados', 'Responsável Comercial', '+55 11 2292-3283', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Brás, São Paulo'),
  ('Tuiuti calçados', 'Responsável Comercial', '+55 11 96635-8006', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Tatuapé, São Paulo'),
  ('Lena chinelos havaianas customizados', 'Responsável Comercial', '+55 11 98062-7902', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Vila Marieta, São Paulo'),
  ('Monfer Indústria de Sapatas e Comercial', 'Responsável Comercial', '+55 11 2771-9518', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Vila Ré, São Paulo'),
  ('Indústria de Calcados Roberto Coelho', 'Responsável Comercial', '+55 11 2093-9323', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Tatuapé, São Paulo'),
  ('FabioeLadycalcadosemcouro', 'Responsável Comercial', '+55 11 99264-0395', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Americanópolis, São Paulo'),
  ('Full Plastic', 'Responsável Comercial', '+55 11 5565-7784', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Vila Santa Catarina, São Paulo'),
  ('Dom Luiz Calçados', 'Responsável Comercial', '+55 11 96404-5614', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Jardim Jussara, São Paulo'),
  ('rs comercio e representacoes de produtos para calçados construção artesanatos ltda', 'Responsável Comercial', '+55 11 5812-8343', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Capão Redondo, São Paulo'),
  ('Sandalia Solemar', 'Responsável Comercial', '+55 11 99151-8418', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Vila Nova York, São Paulo'),
  ('Capricórnio', 'Responsável Comercial', '+55 11 2601-0097', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de tecelagem | Vila Claudia, São Paulo'),
  ('VMP Metais', 'Responsável Comercial', '+55 11 2916-3099', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Metalúrgica | Jardim Independência (São Paulo), São Paulo'),
  ('Lisarb', 'Responsável Comercial', '+55 11 95973-7779', NULL, 'calcados_atacado', 'frio', 'Calçados SP | Atacadista de calçados | Freguesia do Ó, São Paulo'),
  ('Tns do DR', 'Responsável Comercial', '+55 11 95200-4659', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Lageado, São Paulo'),
  ('Luciano Componentes de Calçados', 'Responsável Comercial', '+55 11 94903-3663', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Mooca, São Paulo'),
  ('Walnice-Ciganinha Indústria e Comércio de Calçados', 'Responsável Comercial', '+55 11 2046-3773', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Vila Uniao (Zona Leste), São Paulo'),
  ('Showroom - Topshoes indústria de Calçados SA', 'Responsável Comercial', '+55 54 3285-2700', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Showroom | Jardim Paulista, São Paulo'),
  ('WA Shoes', 'Responsável Comercial', '+55 11 98702-6001', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Conjunto Promorar Sapopemba, São Paulo'),
  ('solestyle calçados', 'Responsável Comercial', '+55 11 91553-9838', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Fábrica de Calçados | Vila Invernada, São Paulo'),
  ('Indústria Comércio Calçados Fascar', 'Responsável Comercial', '+55 11 3865-5140', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja de calçado | Água Branca, São Paulo'),
  ('Brand Shoes', 'Responsável Comercial', '', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Marca/Loja | , Sao Paulo / Grande SP'),
  ('Dilly Sports', 'Responsável Comercial', '', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Marca Esportiva | , Sao Paulo / Grande SP'),
  ('Franca Sapatos', 'Responsável Comercial', '', NULL, 'calcados_varejo', 'frio', 'Calçados SP | Loja (Polo Franca) | , Sao Paulo / Grande SP')
) AS v(empresa, contato_nome, telefone, email, segmento, temperatura, observacoes)
ON CONFLICT DO NOTHING;

COMMIT;

-- Total de leads: 282
-- Quente: 29 | Morno: 26 | Frio: 227
-- Segmentos: calcados_rede(26) | calcados_industria(13) | calcados_atacado(34) | calcados_varejo(209)