// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://vsxzrbremdmcdunwfeuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzeHpyYnJlbWRtY2R1bndmZXV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4NTY1OTQsImV4cCI6MjA4NzQzMjU5NH0.-SLvBcH6PPRcGmNyP0Iv-NSefSBGVJfDQ662ET6sdJQ";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);